export const IMPRINT = `
Impressum:

GoldSax GbR
Blochmannstraße 21B
04105 Leipzig
Deutschland

Tel.: 03425 8359294
E-Mail: info@goldsax-goldwaschen.de

Vertretungsberechtigte Gesellschafter: Sören Kube, Paul Großmann

Umsatzsteuer-Identifikationsnummer: DE326820524

Verantwortliche/r i.S.d. § 18 Abs. 2 MStV:
Sören Kube, Blochmannstraße 21B, 04105 Leipzig

Zuständige Aufsichtsbehörde für das Angebot audiovisueller Mediendienste:
Sächsische Landesmedienanstalt (SLM), Ferdinand-Lassalle-Straße 21, 04109 Leipzig, Deutschland

Wir sind zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle nicht verpflichtet, hierzu jedoch bereit.
`;

export const TERMS = `
Allgemeine Geschäftsbedingungen mit Kundeninformationen

Inhaltsverzeichnis
1. Geltungsbereich
2. Vertragsschluss
3. Widerrufsrecht
4. Preise und Zahlungsbedingungen
5. Liefer- und Versandbedingungen
6. Einräumung von Nutzungsrechten für digitale Inhalte
7. Vertragsdauer und Vertragsbeendigung bei Abonnementverträgen für digitale Inhalte
8. Eigentumsvorbehalt
9. Mängelhaftung (Gewährleistung)
10. Haftung
11. Besondere Bedingungen für die Verarbeitung von Waren nach bestimmten Vorgaben des Kunden
12. Einlösung von Aktionsgutscheinen
13. Einlösung von Geschenkgutscheinen
14. Anwendbares Recht
15. Alternative Streitbeilegung


1) Geltungsbereich
1.1 Diese Allgemeinen Geschäftsbedingungen (nachfolgend „AGB“) der GoldSax GbR (nachfolgend „Verkäufer"), gelten für alle Verträge zur Lieferung von Waren, die ein Verbraucher oder Unternehmer (nachfolgend „Kunde“) mit dem Verkäufer hinsichtlich der vom Verkäufer in seinem Online-Shop dargestellten Waren abschließt. Hiermit wird der Einbeziehung von eigenen Bedingungen des Kunden widersprochen, es sei denn, es ist etwas anderes vereinbart.
1.2 Für Verträge zur Lieferung von Gutscheinen gelten diese AGB entsprechend, sofern insoweit nicht etwas Abweichendes geregelt ist.
1.3 Für Verträge zur Bereitstellung von digitalen Inhalten gelten diese AGB entsprechend, sofern insoweit nicht etwas Abweichendes geregelt ist. Digitale Inhalte im Sinne dieser AGB sind Daten, die in digitaler Form erstellt und bereitgestellt werden.
1.4 Verbraucher im Sinne dieser AGB ist jede natürliche Person, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können.
1.5 Unternehmer im Sinne dieser AGB ist eine natürliche oder juristische Person oder eine rechtsfähige Personengesellschaft, die bei Abschluss eines Rechtsgeschäfts in Ausübung ihrer gewerblichen oder selbständigen beruflichen Tätigkeit handelt.
1.6 Gegenstand des Vertrages kann – je nach Inhaltsbeschreibung des Verkäufers – sowohl die einmalige Bereitstellung von digitalen Inhalten, als auch die regelmäßige Bereitstellung von digitalen Inhalten (nachfolgend „Abonnementvertrag“) sein. Beim Abonnementvertrag verpflichtet sich der Verkäufer, dem Kunden die vertraglich geschuldeten digitalen Inhalte für die Dauer der vereinbarten Vertragslaufzeit in den vertraglich vereinbarten Zeitintervallen bereitzustellen.

2) Vertragsschluss
2.1 Die im Online-Shop des Verkäufers enthaltenen Produktbeschreibungen stellen keine verbindlichen Angebote seitens des Verkäufers dar, sondern dienen zur Abgabe eines verbindlichen Angebots durch den Kunden.
2.2 Der Kunde kann das Angebot über das in den Online-Shop des Verkäufers integrierte Online-Bestellformular abgeben. Dabei gibt der Kunde, nachdem er die ausgewählten Waren in den virtuellen Warenkorb gelegt und den elektronischen Bestellprozess durchlaufen hat, durch Klicken des den Bestellvorgang abschließenden Buttons ein rechtlich verbindliches Vertragsangebot in Bezug auf die im Warenkorb enthaltenen Waren ab. Ferner kann der Kunde das Angebot auch per E-Mail, per Online-Kontaktformular oder telefonisch gegenüber dem Verkäufer abgeben.
2.3 Der Verkäufer kann das Angebot des Kunden innerhalb von fünf Tagen annehmen,
- indem er dem Kunden eine schriftliche Auftragsbestätigung oder eine Auftragsbestätigung in Textform (Fax oder E-Mail) übermittelt, wobei insoweit der Zugang der Auftragsbestätigung beim Kunden maßgeblich ist, oder
- indem er dem Kunden die bestellte Ware liefert, wobei insoweit der Zugang der Ware beim Kunden maßgeblich ist, oder
- indem er den Kunden nach Abgabe von dessen Bestellung zur Zahlung auffordert.
Liegen mehrere der vorgenannten Alternativen vor, kommt der Vertrag in dem Zeitpunkt zustande, in dem eine der vorgenannten Alternativen zuerst eintritt. Die Frist zur Annahme des Angebots beginnt am Tag nach der Absendung des Angebots durch den Kunden zu laufen und endet mit dem Ablauf des fünften Tages, welcher auf die Absendung des Angebots folgt. Nimmt der Verkäufer das Angebot des Kunden innerhalb vorgenannter Frist nicht an, so gilt dies als Ablehnung des Angebots mit der Folge, dass der Kunde nicht mehr an seine Willenserklärung gebunden ist.
2.4 Bei Auswahl einer von PayPal angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister PayPal (Europe) S.à r.l. et Cie, S.C.A., 22-24 Boulevard Royal, L-2449 Luxemburg (im Folgenden: „PayPal“), unter Geltung der PayPal-Nutzungsbedingungen, einsehbar unter https://www.paypal.com/de/legalhub/paypal/useragreement-full oder - falls der Kunde nicht über ein PayPal-Konto verfügt – unter Geltung der Bedingungen für Zahlungen ohne PayPal-Konto, einsehbar unter https://www.paypal.com/de/legalhub/paypal/privacywax-full. Zahlt der Kunde mittels einer im Online-Bestellvorgang auswählbaren von PayPal angebotenen Zahlungsart, erklärt der Verkäufer schon jetzt die Annahme des Angebots des Kunden in dem Zeitpunkt, in dem der Kunde den Button anklickt, welcher den Bestellvorgang abschließt.
2.5 Bei Auswahl der Zahlungsart „Amazon Payments" erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Amazon Payments Europe s.c.a., 38 avenue John F. Kennedy, L-1855 Luxemburg (im Folgenden: „Amazon“), unter Geltung der Amazon Payments Europe Nutzungsvereinbarung, einsehbar unter https://pay.amazon.de/help/201751590. Wählt der Kunde im Rahmen des Online-Bestellvorgangs „Amazon Payments“ als Zahlungsart aus, erteilt er durch Klicken des den Bestellvorgang abschließenden Buttons zugleich auch einen Zahlungsauftrag an Amazon. Für diesen Fall erklärt der Verkäufer schon jetzt die Annahme des Angebots des Kunden in dem Zeitpunkt, in dem der Kunde durch Klicken des den Bestellvorgang abschließenden Buttons den Zahlungsvorgang auslöst.
2.6 Bei der Abgabe eines Angebots über das Online-Bestellformular des Verkäufers wird der Vertragstext nach dem Vertragsschluss vom Verkäufer gespeichert und dem Kunden nach Absendung von dessen Bestellung in Textform (z. B. E-Mail, Fax oder Brief) übermittelt. Eine darüber hinausgehende Zugänglichmachung des Vertragstextes durch den Verkäufer erfolgt nicht. Sofern der Kunde vor Absendung seiner Bestellung ein Nutzerkonto im Online-Shop des Verkäufers eingerichtet hat, werden die Bestelldaten auf der Website des Verkäufers archiviert und können vom Kunden über dessen passwortgeschütztes Nutzerkonto unter Angabe der entsprechenden Login-Daten kostenlos abgerufen werden.
2.7 Vor verbindlicher Abgabe der Bestellung über das Online-Bestellformular des Verkäufers kann der Kunde mögliche Eingabefehler durch aufmerksames Lesen der auf dem Bildschirm dargestellten Informationen erkennen. Ein wirksames technisches Mittel zur besseren Erkennung von Eingabefehlern kann dabei die Vergrößerungsfunktion des Browsers sein, mit deren Hilfe die Darstellung auf dem Bildschirm vergrößert wird. Seine Eingaben kann der Kunde im Rahmen des elektronischen Bestellprozesses so lange über die üblichen Tastatur- und Mausfunktionen korrigieren, bis er den Button anklickt, welcher den Bestellvorgang abschließt.
2.8 Für den Vertragsschluss stehen unterschiedliche Sprachen zur Verfügung. Die konkrete Sprachauswahl wird im Online-Shop angezeigt.
2.9 Die Bestellabwicklung und Kontaktaufnahme finden in der Regel per E-Mail und automatisierter Bestellabwicklung statt. Der Kunde hat sicherzustellen, dass die von ihm zur Bestellabwicklung angegebene E-Mail-Adresse zutreffend ist, so dass unter dieser Adresse die vom Verkäufer versandten E-Mails empfangen werden können. Insbesondere hat der Kunde bei dem Einsatz von SPAM-Filtern sicherzustellen, dass alle vom Verkäufer oder von diesem mit der Bestellabwicklung beauftragten Dritten versandten E-Mails zugestellt werden können.

3) Widerrufsrecht
3.1 Verbrauchern steht grundsätzlich ein Widerrufsrecht zu.
3.2 Nähere Informationen zum Widerrufsrecht ergeben sich aus der Widerrufsbelehrung des Verkäufers.

4) Preise und Zahlungsbedingungen
4.1 Sofern sich aus der Produktbeschreibung des Verkäufers nichts anderes ergibt, handelt es sich bei den angegebenen Preisen um Gesamtpreise, die die gesetzliche Umsatzsteuer enthalten. Gegebenenfalls zusätzlich anfallende Liefer- und Versandkosten werden in der jeweiligen Produktbeschreibung gesondert angegeben.
4.2 Bei Lieferungen in Länder außerhalb der Europäischen Union können im Einzelfall weitere Kosten anfallen, die der Verkäufer nicht zu vertreten hat und die vom Kunden zu tragen sind. Hierzu zählen beispielsweise Kosten für die Geldübermittlung durch Kreditinstitute (z.B. Überweisungsgebühren, Wechselkursgebühren) oder einfuhrrechtliche Abgaben bzw. Steuern (z.B. Zölle). Solche Kosten können in Bezug auf die Geldübermittlung auch dann anfallen, wenn die Lieferung nicht in ein Land außerhalb der Europäischen Union erfolgt, der Kunde die Zahlung aber von einem Land außerhalb der Europäischen Union aus vornimmt.
4.3 Die Zahlungsmöglichkeit/en wird/werden dem Kunden im Online-Shop des Verkäufers mitgeteilt.
4.4 Ist Vorauskasse per Banküberweisung vereinbart, ist die Zahlung sofort nach Vertragsabschluss fällig, sofern die Parteien keinen späteren Fälligkeitstermin vereinbart haben.
4.5 Bei Auswahl einer über den Zahlungsdienst „PayPal“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über PayPal, wobei sich PayPal hierzu auch der Dienste dritter Zahlungsdienstleister bedienen kann. Sofern der Verkäufer über PayPal auch Zahlungsarten anbietet, bei denen er gegenüber dem Kunden in Vorleistung geht (z. B. Rechnungskauf oder Ratenzahlung), tritt er seine Zahlungsforderung insoweit an PayPal bzw. an den von PayPal beauftragten und dem Kunden konkret benannten Zahlungsdienstleister ab. Vor Annahme der Abtretungserklärung des Verkäufers führt PayPal bzw. der von PayPal beauftragte Zahlungsdienstleister unter Verwendung der übermittelten Kundendaten eine Bonitätsprüfung durch. Der Verkäufer behält sich vor, dem Kunden die ausgewählte Zahlungsart im Falle eines negativen Prüfungsergebnisses zu verweigern. Bei Zulassung der ausgewählten Zahlungsart hat der Kunde den Rechnungsbetrag innerhalb der vereinbarten Zahlungsfrist bzw. in den vereinbarten Zahlungsintervallen zu bezahlen. Er kann in diesem Fall nur an PayPal bzw. den von PayPal beauftragten Zahlungsdienstleister mit schuldbefreiender Wirkung leisten. Der Verkäufer bleibt jedoch auch im Falle der Forderungsabtretung zuständig für allgemeine Kundenanfragen z. B. zur Ware, Lieferzeit, Versendung, Retouren, Reklamationen, Widerrufserklärungen und -zusendungen oder Gutschriften.
4.6 Bei Auswahl der Zahlungsart "Sofortüberweisung" erfolgt die Zahlungsabwicklung durch die Klarna Bank AB (publ), Sveavägen 46, 11134 Stockholm, Schweden (im Folgenden "Klarna"). Um den Rechnungsbetrag via "Sofortüberweisung" bezahlen zu können, muss der Kunde über ein für die Teilnahme an "Sofortüberweisung" freigeschaltetes Online-Banking-Konto verfügen, sich beim Zahlungsvorgang entsprechend legitimieren und die Zahlungsanweisung bestätigen. Die Zahlungstransaktion wird unmittelbar danach von Klarna durchgeführt und das Bankkonto des Kunden belastet. Nähere Informationen zur Zahlungsart "Sofortüberweisung" kann der Kunde im Internet unter https://www.klarna.com/sofort/ abrufen.
4.7 Bei Auswahl einer über den Zahlungsdienst "Shopify Payments" angebotenen Zahlungsart erfolgt die Zahlungsabwicklung durch den Zahlungsdienstleister Stripe Payments Europe Ltd., 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland (nachfolgend "Stripe"). Die einzelnen über Shopify Payments angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Stripe weiterer Zahlungsdienste bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu "Shopify Payments" sind im Internet unter https://www.shopify.com/legal/terms-payments-de abrufbar.
4.8 Bei Auswahl einer über den Zahlungsdienst "Mollie" angebotenen Zahlungsart erfolgt die Zahlungsabwicklung durch den Zahlungsdienstleister Mollie B.V., Keizersgracht 313, 1016 EE Amsterdam, Niederlande (im Folgenden: „mollie“). Die einzelnen über Mollie angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Mollie weiterer Zahlungsdienste bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu "Mollie" sind im Internet unter https://www.mollie.com/de/ abrufbar.
4.9 Bei Auswahl einer über den Zahlungsdienst „Adyen“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Adyen N.V., Simon Carmiggeltstraat 6-50, 1011 DJ, Amsterdam, Niederlande (im Folgenden: „Adyen“). Die einzelnen über Adyen angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Adyen der Dienste dritter Zahlungsdienstleister bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu "Adyen" sind im Internet unter https://www.adyen.help/hc/de abrufbar.
4.10 Bei Auswahl einer über den Zahlungsdienst „Unzer“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Unzer Group GmbH, Schöneberger Str. 21 a,10963 Berlin, Deutschland (im Folgenden: „Unzer“). Die einzelnen über Unzer angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Unzer der Dienste dritter Zahlungsdienstleister bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu "Unzer" sind im Internet unter https://www.unzer.com/de/zahlungsmethoden/ abrufbar.
4.11 Bei Auswahl einer über den Zahlungsdienst „Stripe“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Stripe Payments Europe Ltd., 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland (nachfolgend "Stripe"). Die einzelnen über Stripe angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Stripe weiterer Zahlungsdienste bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu Stripe sind im Internet unter https://stripe.com/de abrufbar.
4.12 Bei Auswahl einer über den Zahlungsdienst „SumUp“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister SumUp Limited, Block 8, Harcourt Centre, Charlotte Way, Dublin 2, Irland D02 K580 (nachfolgend "SumUp"). Die einzelnen über Stripe angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich SumUp weiterer Zahlungsdienste bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu SumUp sind im Internet unter https://www.sumup.com/de-de/ abrufbar.
4.13 Bei Auswahl einer über den Zahlungsdienst „Wix Payments“ angebotenen Zahlungsart erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Wix HQ, 6350671, Nemal Tel Aviv St 40, Tel Aviv-Yafo, Israel (nachfolgend „Wix“). Die einzelnen über Wix angebotenen Zahlungsarten werden dem Kunden im Online-Shop des Verkäufers mitgeteilt. Zur Abwicklung von Zahlungen kann sich Wix weiterer Zahlungsdienste bedienen, für die ggf. besondere Zahlungsbedingungen gelten, auf die der Kunde ggf. gesondert hingewiesen wird. Weitere Informationen zu Wix Payments sind im Internet unter https://de.wix.com/payments abrufbar.
4.14 Bei Auswahl der Zahlungsart „PayPal Lastschrift“ zieht PayPal den Rechnungsbetrag nach Erteilung eines SEPA-Lastschriftmandats, nicht jedoch vor Ablauf der Frist für die Vorabinformation im Auftrag des Verkäufers vom Bankkonto des Kunden ein. Vorabinformation ("Pre-Notification") ist jede Mitteilung (z.B. Rechnung, Police, Vertrag) an den Kunden, die eine Belastung mittels SEPA-Lastschrift ankündigt. Wird die Lastschrift mangels ausreichender Kontodeckung oder aufgrund der Angabe einer falschen Bankverbindung nicht eingelöst oder widerspricht der Kunde der Abbuchung, obwohl er hierzu nicht berechtigt ist, hat der Kunde die durch die Rückbuchung des jeweiligen Kreditinstituts entstehenden Gebühren zu tragen, wenn er dies zu vertreten hat.
4.15 Bei Auswahl der Zahlungsart Lastschrift via Stripe erfolgt die Zahlungsabwicklung über den Zahlungsdienstleister Stripe Payments Europe Ltd., 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland (im Folgenden: „Stripe“). In diesem Fall zieht Stripe den Rechnungsbetrag nach Erteilung eines SEPA-Lastschriftmandats, nicht jedoch vor Ablauf der Frist für die Vorabinformation im Auftrag des Verkäufers vom Bankkonto des Kunden ein. Vorabinformation ("Pre-Notification") ist jede Mitteilung (z.B. Rechnung, Police, Vertrag) an den Kunden, die eine Belastung mittels SEPA-Lastschrift ankündigt. Wird die Lastschrift mangels ausreichender Kontodeckung oder aufgrund der Angabe einer falschen Bankverbindung nicht eingelöst oder widerspricht der Kunde der Abbuchung, obwohl er hierzu nicht berechtigt ist, hat der Kunde die durch die Rückbuchung des jeweiligen Kreditinstituts entstehenden Gebühren zu tragen, wenn er dies zu vertreten hat. Der Verkäufer behält sich vor, bei Auswahl der Zahlungsart SEPA-Lastschrift eine Bonitätsprüfung durchzuführen und diese Zahlungsart bei negativer Bonitätsprüfung abzulehnen.
4.16 Bei Auswahl der Zahlungsart Kreditkarte via Stripe ist der Rechnungsbetrag mit Vertragsschluss sofort fällig. Die Zahlungsabwicklung erfolgt über den Zahlungsdienstleister Stripe Payments Europe Ltd., 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland (im Folgenden: „Stripe“). Stripe behält sich vor, eine Bonitätsprüfung durchzuführen und diese Zahlungsart bei negativer Bonitätsprüfung abzulehnen.

5) Liefer- und Versandbedingungen
5.1 Bietet der Verkäufer den Versand der Ware an, so erfolgt die Lieferung innerhalb des vom Verkäufer angegebenen Liefergebietes an die vom Kunden angegebene Lieferanschrift, sofern nichts anderes vereinbart ist. Bei der Abwicklung der Transaktion ist die in der Bestellabwicklung des Verkäufers angegebene Lieferanschrift maßgeblich.
5.2 Scheitert die Zustellung der Ware aus Gründen, die der Kunde zu vertreten hat, trägt der Kunde die dem Verkäufer hierdurch entstehenden angemessenen Kosten. Dies gilt im Hinblick auf die Kosten für die Hinsendung nicht, wenn der Kunde sein Widerrufsrecht wirksam ausübt. Für die Rücksendekosten gilt bei wirksamer Ausübung des Widerrufsrechts durch den Kunden die in der Widerrufsbelehrung des Verkäufers hierzu getroffene Regelung.
5.3 Handelt der Kunde als Unternehmer, geht die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung der verkauften Ware auf den Kunden über, sobald der Verkäufer die Sache dem Spediteur, dem Frachtführer oder der sonst zur Ausführung der Versendung bestimmten Person oder Anstalt ausgeliefert hat. Handelt der Kunde als Verbraucher, geht die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung der verkauften Ware grundsätzlich erst mit Übergabe der Ware an den Kunden oder eine empfangsberechtigte Person über. Abweichend hiervon geht die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung der verkauften Ware auch bei Verbrauchern bereits auf den Kunden über, sobald der Verkäufer die Sache dem Spediteur, dem Frachtführer oder der sonst zur Ausführung der Versendung bestimmten Person oder Anstalt ausgeliefert hat, wenn der Kunde den Spediteur, den Frachtführer oder die sonst zur Ausführung der Versendung bestimmte Person oder Anstalt mit der Ausführung beauftragt und der Verkäufer dem Kunden diese Person oder Anstalt zuvor nicht benannt hat.
5.4 Der Verkäufer behält sich das Recht vor, im Falle nicht richtiger oder nicht ordnungsgemäßer Selbstbelieferung vom Vertrag zurückzutreten. Dies gilt nur für den Fall, dass die Nichtlieferung nicht vom Verkäufer zu vertreten ist und dieser mit der gebotenen Sorgfalt ein konkretes Deckungsgeschäft mit dem Zulieferer abgeschlossen hat. Der Verkäufer wird alle zumutbaren Anstrengungen unternehmen, um die Ware zu beschaffen. Im Falle der Nichtverfügbarkeit oder der nur teilweisen Verfügbarkeit der Ware wird der Kunde unverzüglich informiert und die Gegenleistung unverzüglich erstattet.
5.5 Bietet der Verkäufer die Ware zur Abholung an, so kann der Kunde die bestellte Ware innerhalb der vom Verkäufer angegebenen Geschäftszeiten unter der vom Verkäufer angegebenen Adresse abholen. In diesem Fall werden keine Versandkosten berechnet.
5.6 Gutscheine werden dem Kunden wie folgt bereitgestellt:
- per Download
- per E-Mail
5.7 Digitale Inhalte werden dem Kunden wie folgt bereitgestellt:
- per Direktzugriff über die Website des Unternehmers
- per Download
- per E-Mail

6) Einräumung von Nutzungsrechten für digitale Inhalte
6.1 Sofern sich aus der Inhaltsbeschreibung im Online-Shop des Verkäufers nichts anderes ergibt, räumt der Verkäufer dem Kunden an den bereitgestellten Inhalten das nicht ausschließliche, örtlich und zeitlich unbeschränkte Recht ein, die Inhalte zu privaten sowie zu kommerziellen Zwecken zu nutzen.
6.2 Eine Weitergabe der Inhalte an Dritte oder die Erstellung von Kopien für Dritte außerhalb des Rahmens dieser AGB ist nicht gestattet, soweit nicht der Verkäufer einer Übertragung der vertragsgegenständlichen Lizenz an den Dritten zugestimmt hat.
6.3 Soweit sich der Vertrag auf die einmalige Bereitstellung eines digitalen Inhalts bezieht, wird die Rechtseinräumung erst wirksam, wenn der Kunde die geschuldete Vergütung vollständig geleistet hat. Der Verkäufer kann eine Benutzung der vertragsgegenständlichen Inhalte auch schon vor diesem Zeitpunkt vorläufig erlauben. Ein Übergang der Rechte findet durch eine solche vorläufige Erlaubnis nicht statt.

7) Vertragsdauer und Vertragsbeendigung bei Abonnementverträgen für digitale Inhalte
7.1 Abonnementverträge werden unbefristet geschlossen und können vom Kunden jederzeit ohne Einhaltung einer Kündigungsfrist gekündigt werden.
7.2 Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt. Ein wichtiger Grund liegt vor, wenn dem kündigenden Teil unter Berücksichtigung aller Umstände des Einzelfalls und unter Abwägung der beiderseitigen Interessen die Fortsetzung des Vertragsverhältnisses bis zur vereinbarten Beendigung oder bis zum Ablauf einer Kündigungsfrist nicht zugemutet werden kann.
7.3 Kündigungen haben schriftlich oder in Textform (z. B. per E-Mail) zu erfolgen.

8) Eigentumsvorbehalt
Tritt der Verkäufer in Vorleistung, behält er sich bis zur vollständigen Bezahlung des geschuldeten Kaufpreises das Eigentum an der gelieferten Ware vor.

9) Mängelhaftung (Gewährleistung)
Soweit sich aus den nachfolgenden Regelungen nichts anderes ergibt, gelten die Vorschriften der gesetzlichen Mängelhaftung. Hiervon abweichend gilt bei Verträgen zur Lieferung von Waren:
9.1 Handelt der Kunde als Unternehmer,
- hat der Verkäufer die Wahl der Art der Nacherfüllung;
- beträgt bei neuen Waren die Verjährungsfrist für Mängelrechte ein Jahr ab Ablieferung der Ware;
- sind bei gebrauchten Waren die Mängelrechte ausgeschlossen;
- beginnt die Verjährung nicht erneut, wenn im Rahmen der Mängelhaftung eine Ersatzlieferung erfolgt.
9.2 Die vorstehend geregelten Haftungsbeschränkungen und Fristverkürzungen gelten nicht
- für Schadensersatz- und Aufwendungsersatzansprüche des Kunden,
- für den Fall, dass der Verkäufer den Mangel arglistig verschwiegen hat,
- für Waren, die entsprechend ihrer üblichen Verwendungsweise für ein Bauwerk verwendet worden sind und dessen Mangelhaftigkeit verursacht haben,
- für eine ggf. bestehende Verpflichtung des Verkäufers zur Bereitstellung von Aktualisierungen für digitale Produkte, bei Verträgen zur Lieferung von Waren mit digitalen Elementen.
9.3 Darüber hinaus gilt für Unternehmer, dass die gesetzlichen Verjährungsfristen für einen ggf. bestehenden gesetzlichen Rückgriffsanspruch unberührt bleiben.
9.4 Handelt der Kunde als Kaufmann i.S.d. § 1 HGB, trifft ihn die kaufmännische Untersuchungs- und Rügepflicht gemäß § 377 HGB. Unterlässt der Kunde die dort geregelten Anzeigepflichten, gilt die Ware als genehmigt.
9.5 Handelt der Kunde als Verbraucher, so wird er gebeten, angelieferte Waren mit offensichtlichen Transportschäden bei dem Zusteller zu reklamieren und den Verkäufer hiervon in Kenntnis zu setzen. Kommt der Kunde dem nicht nach, hat dies keinerlei Auswirkungen auf seine gesetzlichen oder vertraglichen Mängelansprüche.

10) Haftung
Der Verkäufer haftet dem Kunden aus allen vertraglichen, vertragsähnlichen und gesetzlichen, auch deliktischen Ansprüchen auf Schadens- und Aufwendungsersatz wie folgt:
10.1 Der Verkäufer haftet aus jedem Rechtsgrund uneingeschränkt
- bei Vorsatz oder grober Fahrlässigkeit,
- bei vorsätzlicher oder fahrlässiger Verletzung des Lebens, des Körpers oder der Gesundheit,
- aufgrund eines Garantieversprechens, soweit diesbezüglich nichts anderes geregelt ist,
- aufgrund zwingender Haftung wie etwa nach dem Produkthaftungsgesetz.
10.2 Verletzt der Verkäufer fahrlässig eine wesentliche Vertragspflicht, ist die Haftung auf den vertragstypischen, vorhersehbaren Schaden begrenzt, sofern nicht gemäß vorstehender Ziffer unbeschränkt gehaftet wird. Wesentliche Vertragspflichten sind Pflichten, die der Vertrag dem Verkäufer nach seinem Inhalt zur Erreichung des Vertragszwecks auferlegt, deren Erfüllung die ordnungsgemäße Durchführung des Vertrags überhaupt erst ermöglicht und auf deren Einhaltung der Kunde regelmäßig vertrauen darf.
10.3 Im Übrigen ist eine Haftung des Verkäufers ausgeschlossen.
10.4 Vorstehende Haftungsregelungen gelten auch im Hinblick auf die Haftung des Verkäufers für seine Erfüllungsgehilfen und gesetzlichen Vertreter.

11) Besondere Bedingungen für die Verarbeitung von Waren nach bestimmten Vorgaben des Kunden
11.1 Schuldet der Verkäufer nach dem Inhalt des Vertrages neben der Warenlieferung auch die Verarbeitung der Ware nach bestimmten Vorgaben des Kunden, hat der Kunde dem Verkäufer alle für die Verarbeitung erforderlichen Inhalte wie Texte, Bilder oder Grafiken in den vom Verkäufer vorgegebenen Dateiformaten, Formatierungen, Bild- und Dateigrößen zur Verfügung zu stellen und ihm die hierfür erforderlichen Nutzungsrechte einzuräumen. Für die Beschaffung und den Rechteerwerb an diesen Inhalten ist allein der Kunde verantwortlich. Der Kunde erklärt und übernimmt die Verantwortung dafür, dass er das Recht besitzt, die dem Verkäufer überlassenen Inhalte zu nutzen. Er trägt insbesondere dafür Sorge, dass hierdurch keine Rechte Dritter verletzt werden, insbesondere Urheber-, Marken- und Persönlichkeitsrechte.
11.2 Der Kunde stellt den Verkäufer von Ansprüchen Dritter frei, die diese im Zusammenhang mit einer Verletzung ihrer Rechte durch die vertragsgemäße Nutzung der Inhalte des Kunden durch den Verkäufer diesem gegenüber geltend machen können. Der Kunde übernimmt hierbei auch die notwendigen Kosten der Rechtsverteidigung einschließlich aller Gerichts- und Anwaltskosten in gesetzlicher Höhe. Dies gilt nicht, wenn die Rechtsverletzung vom Kunden nicht zu vertreten ist. Der Kunde ist verpflichtet, dem Verkäufer im Falle einer Inanspruchnahme durch Dritte unverzüglich, wahrheitsgemäß und vollständig alle Informationen zur Verfügung zu stellen, die für die Prüfung der Ansprüche und eine Verteidigung erforderlich sind.
11.3 Der Verkäufer behält sich vor, Verarbeitungsaufträge abzulehnen, wenn die vom Kunden hierfür überlassenen Inhalte gegen gesetzliche oder behördliche Verbote oder gegen die guten Sitten verstossen. Dies gilt insbesondere bei Überlassung verfassungsfeindlicher, rassistischer, fremdenfeindlicher, diskriminierender, beleidigender, Jugend gefährdender und/oder Gewalt verherrlichender Inhalte.

12) Einlösung von Aktionsgutscheinen
12.1 Gutscheine, die vom Verkäufer im Rahmen von Werbeaktionen mit einer bestimmten Gültigkeitsdauer unentgeltlich ausgegeben werden und die vom Kunden nicht käuflich erworben werden können (nachfolgend "Aktionsgutscheine"), können nur im Online-Shop des Verkäufers und nur im angegebenen Zeitraum eingelöst werden.
12.2 Einzelne Produkte können von der Gutscheinaktion ausgeschlossen sein, sofern sich eine entsprechende Einschränkung aus dem Inhalt des Aktionsgutscheins ergibt.
12.3 Aktionsgutscheine können nur vor Abschluss des Bestellvorgangs eingelöst werden. Eine nachträgliche Verrechnung ist nicht möglich.
12.4 Pro Bestellung kann immer nur ein Aktionsgutschein eingelöst werden.
12.5 Sofern sich der Aktionsgutschein auf einen konkreten Wert und nicht auf einen prozentualen Preisnachlass bezieht, muss der Warenwert mindestens dem Betrag des Aktionsgutscheins entsprechen. Etwaiges Restguthaben wird vom Verkäufer nicht erstattet.
12.6 Reicht der Wert des Aktionsgutscheins zur Deckung der Bestellung nicht aus, kann zur Begleichung des Differenzbetrages eine der übrigen vom Verkäufer angebotenen Zahlungsarten gewählt werden.
12.7 Das Guthaben eines Aktionsgutscheins wird weder in Bargeld ausgezahlt noch verzinst.
12.8 Der Aktionsgutschein wird nicht erstattet, wenn der Kunde die mit dem Aktionsgutschein ganz oder teilweise bezahlte Ware im Rahmen seines gesetzlichen Widerrufsrechts zurückgibt.
12.9 Der Aktionsgutschein ist übertragbar. Der Verkäufer kann mit befreiender Wirkung an den jeweiligen Inhaber, der den Aktionsgutschein im Online-Shop des Verkäufers einlöst, leisten. Dies gilt nicht, wenn der Verkäufer Kenntnis oder grob fahrlässige Unkenntnis von der Nichtberechtigung, der Geschäftsunfähigkeit oder der fehlenden Vertretungsberechtigung des jeweiligen Inhabers hat.

13) Einlösung von Geschenkgutscheinen
13.1 Gutscheine, die über den Online-Shop des Verkäufers käuflich erworben werden können (nachfolgend "Geschenkgutscheine"), können nur im Online-Shop des Verkäufers eingelöst werden, sofern sich aus dem Gutschein nichts anderes ergibt.
13.2 Geschenkgutscheine und Restguthaben von Geschenkgutscheinen sind bis zum Ende des dritten Jahres nach dem Jahr des Gutscheinkaufs einlösbar. Restguthaben werden dem Kunden bis zum Ablaufdatum gutgeschrieben.
13.3 Geschenkgutscheine können nur vor Abschluss des Bestellvorgangs eingelöst werden. Eine nachträgliche Verrechnung ist nicht möglich.
13.4 Pro Bestellung kann immer nur ein Geschenkgutschein eingelöst werden.
13.5 Geschenkgutscheine können nur für den Kauf von Waren und nicht für den Kauf von weiteren Geschenkgutscheinen verwendet werden.
13.6 Reicht der Wert des Geschenkgutscheins zur Deckung der Bestellung nicht aus, kann zur Begleichung des Differenzbetrages eine der übrigen vom Verkäufer angebotenen Zahlungsarten gewählt werden.
13.7 Das Guthaben eines Geschenkgutscheins wird weder in Bargeld ausgezahlt noch verzinst.
13.8 Der Geschenkgutschein ist übertragbar. Der Verkäufer kann mit befreiender Wirkung an den jeweiligen Inhaber, der den Geschenkgutschein im Online-Shop des Verkäufers einlöst, leisten. Dies gilt nicht, wenn der Verkäufer Kenntnis oder grob fahrlässige Unkenntnis von der Nichtberechtigung, der Geschäftsunfähigkeit oder der fehlenden Vertretungsberechtigung des jeweiligen Inhabers hat.

14) Anwendbares Recht
Für sämtliche Rechtsbeziehungen der Parteien gilt das Recht der Bundesrepublik Deutschland unter Ausschluss der Gesetze über den internationalen Kauf beweglicher Waren. Bei Verbrauchern gilt diese Rechtswahl nur insoweit, als nicht der gewährte Schutz durch zwingende Bestimmungen des Rechts des Staates, in dem der Verbraucher seinen gewöhnlichen Aufenthalt hat, entzogen wird.

15) Alternative Streitbeilegung
Der Verkäufer ist zur Teilnahme an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle nicht verpflichtet, hierzu aber bereit.


Copyright-Hinweis: Diese AGB wurden von den Fachanwälten der IT-Recht Kanzlei erstellt und sind urheberrechtlich geschützt (https://www.it-recht-kanzlei.de)
`;

export const PRIVACY_POLICY = `
1) Information über die Erhebung personenbezogener Daten und Kontaktdaten des Verantwortlichen
1.1 Wir freuen uns, dass Sie unsere Applikation (nachfolgend „App“) verwenden. Im Folgenden informieren wir Sie über den Umgang mit Ihren personenbezogenen Daten bei der Nutzung unserer App. Personenbezogene Daten sind hierbei alle Daten, mit denen Sie persönlich identifiziert werden können.
1.2 Verantwortlicher für die Datenverarbeitung bezüglich dieser App im Sinne der Datenschutz-Grundverordnung (DSGVO) ist GoldSax GbR, Blochmannstraße 21B, 04105 Leipzig, Deutschland, Tel.: 03425 8359294, E-Mail: info@goldsax-goldwaschen.de. Der für die Verarbeitung von personenbezogenen Daten Verantwortliche ist diejenige natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten entscheidet.
1.3 Diese App nutzt aus Sicherheitsgründen und zum Schutz der Übertragung personenbezogene Daten und anderer vertraulicher Inhalte (z.B. Bestellungen oder Anfragen an den Verantwortlichen) eine SSL-bzw. TLS-Verschlüsselung. Sie können eine verschlüsselte Verbindung an der Zeichenfolge „https://“ und dem Schloss-Symbol in Ihrer Browserzeile erkennen.

2) Verwendung von Single-Sign-On-Verfahren
Google Sign-In
In unserer App stellen wir eine Single-Sign-On-Funktion des folgenden Anbieters bereit: Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland
Neben einer Übermittlung von Daten an den o.g. Anbieterstandort können Daten auch übermittelt werden an: Google LLC, USA
Wenn Sie über einen Account beim Anbieter verfügen, können Sie sich mit diesen Accountdaten zur Erstellung eines Benutzerkontos bzw. zur Registrierung auf unserer Website anmelden.
Beim Besuch dieser Seite kann über diese Anmeldefunktion eine direkte Verbindung zwischen Ihrem Browser und den Servern des Anbieters hergestellt werden, auch wenn Sie keinen Account beim Anbieter besitzen oder nicht in einen solchen eingeloggt sind. Der Anbieter erhält dadurch die Information, dass Sie unsere Seite besucht haben. Die insofern erhobenen Informationen (ggf. einschließlich Ihrer IP-Adresse) werden von Ihrem Browser direkt an einen Server des Anbieters übermittelt und dort gespeichert. Die Informationen werden jedoch nicht dazu verwendet, Sie persönlich zu identifizieren, und werden nicht an Dritte weitergegeben.
Diese Datenverarbeitungsvorgänge erfolgen gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an einer nutzerfreundlichen und interaktiven Ausgestaltung unseres Online-Auftritts.
Betätigen Sie den Anmeldebutton, um sich mit den Daten Ihres Accounts beim Anbieter auf unserer Website zu registrieren, übermittelt der Anbieter ausschließlich auf Basis Ihrer ausdrücklichen Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO die in Ihrem Account hinterlegten allgemeinen und öffentlichen zugänglichen Informationen (Nutzer-ID, Name, Anschrift, Mailadresse, Alter und Geschlecht) an uns.
Wir speichern und verwenden die vom Anbieter übermittelten Daten zur Einrichtung eines Benutzerkontos mit den notwendigen Daten (Anrede, Vorname, Nachname, Adressdaten, Land, E-Mail-Adresse, Geburtsdatum), sofern Sie diese gegenüber dem Anbieter freigegeben haben. Umgekehrt können auf Basis Ihrer Einwilligung Daten (z.B. Informationen über Ihr Surf- oder Kaufverhalten) von uns auf Ihren Account beim Anbieter übertragen werden.
Die erteilte Einwilligung kann jederzeit mit Wirkung für die Zukunft uns gegenüber widerrufen werden.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt.
Weitere Hinweise zu den Datenschutzbestimmungen von Google finden sich hier: https://business.safety.google/intl/de/privacy/

3) Logfiles bei Nutzung unserer mobilen App
Wenn Sie unsere mobile App über einen App-Store herunterladen, werden die erforderlichen Informationen an den App Store übertragen, also insbesondere Nutzername, E-Mail-Adresse und Kundennummer Ihres Accounts, Zeitpunkt des Downloads, Zahlungsinformationen und die individuelle Gerätekennziffer. Auf diese Datenerhebung haben wir keinen Einfluss und sind hierfür nicht verantwortlich. Wir verarbeiten die Daten nur, soweit es für das Herunterladen der mobilen App auf Ihr mobiles Endgerät notwendig ist.
Bei Nutzung unserer mobilen App erheben wir die nachfolgend beschriebenen personenbezogenen Daten, um die komfortable Nutzung der Funktion zu ermöglichen. Wenn Sie unsere mobile App nutzen möchten, erheben wir die folgenden Daten, die für uns technisch erforderlich sind, um Ihnen die Funktionen unserer mobilen App anzubieten und die Stabilität und Sicherheit zu gewährleisten:
- Datum und Uhrzeit der Anfrage
- Zeitzonendifferenz zur Greenwich Mean Time (GMT)
- Inhalt der Anforderung
- Zugriffsstatus/ http-Statuscode
- Menge der gesendeten Daten in Byte
- Quelle/Verweis, von welchem Sie auf die Seite gelangten
- Verwendeter Browser
- Sprache und Version der Browsersoftware
- Verwendetes Betriebssystem und dessen Oberfläche
- Verwendete IP-Adresse (ggf.: in anonymisierter Form)
Die Verarbeitung erfolgt gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis unseres berechtigten Interesses an der Verbesserung der Stabilität und Funktionalität unserer App. Eine Weitergabe oder anderweitige Verwendung der Daten findet nicht statt. Wir behalten uns allerdings vor, die vorbenannten Logfiles nachträglich zu überprüfen, sollten konkrete Anhaltspunkte auf eine rechtswidrige Nutzung hinweisen.
Weiterhin benötigen wir Ihre eindeutige Nummer des Endgeräts (IMEI = International Mobile Equipment Identity), eindeutige Nummer des Netzteilnehmers (IMSI = International Mobile Subscriber Identity), Mobilfunknummer (MSISDN), evtl. MAC-Adresse für die WLAN-Nutzung und den Namen Ihres mobilen Endgerätes.

4) Hosting & Content-Delivery-Network
Firebase Cloud Storage
Wir nutzen den Webhosting-Dienst „Firebase Cloud Storage“ der Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland („Google“) zum Zwecke des Hostings und der Darstellung der App-Inhalte auf Basis einer Verarbeitung in unserem Auftrag.
Sämtliche in der App erhobenen Daten werden auf den Servern von Google verarbeitet.
Im Rahmen der vorgenannten Leistungen können Daten auch im Rahmen einer weiteren Verarbeitung im Auftrag an Server der Google LLC. in den USA übermittelt werden. Wir haben mit Google für die Nutzung von Firebase einen Auftragsverarbeitungsvertrag abgeschlossen, mit dem Google verpflichtet wird, die Daten unserer Seitenbesucher zu schützen und sie nicht an Dritte weiter zu geben.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt. Weitere Hinweise zum Datenschutz von Google in Bezug auf Firebase erhalten Sie unter der nachstehenden Internetseite: https://firebase.google.com/support/privacy
Eine weitere Verarbeitung auf anderen Servern als den vorgenannten von Google findet nur im nachstehend mitgeteilten Rahmen statt.

5) Cookies
Um unsere App attraktiv zu gestalten und die Nutzung bestimmter Funktionen zu ermöglichen, verwenden wir sogenannte Cookies. Hierbei handelt es sich um kleine Textdateien, die auf Ihrem Endgerät abgelegt werden. Einige der von uns verwendeten Cookies werden nach dem Schließen der App wieder gelöscht (sog. Sitzungs-Cookies). Andere Cookies verbleiben auf Ihrem Endgerät und ermöglichen uns Sie wiederzuerkennen (sog. persistente Cookies). Werden Cookies gesetzt, erheben und verarbeiten diese im individuellen Umfang bestimmte Nutzerinformationen wie Browser- und Standortdaten sowie IP-Adresswerte. Persistente Cookies werden automatisiert nach einer vorgegebenen Dauer gelöscht, die sich je nach Cookie unterscheiden kann.
Teilweise dienen die Cookies dazu, durch Speicherung von Einstellungen den Betrieb der App zu vereinfachen. Sofern durch einzelne von uns eingesetzte Cookies auch personenbezogene Daten verarbeitet werden, erfolgt die Verarbeitung gemäß Art. 6 Abs. 1 lit. b DSGVO zur Durchführung des Vertrages, gemäß Art. 6 Abs. 1 lit. a DSGVO im Falle einer erteilten Einwilligung oder gemäß Art. 6 Abs. 1 lit. f DSGVO zur Wahrung unserer berechtigten Interessen an der bestmöglichen Funktionalität der App sowie einer kundenfreundlichen und effektiven Ausgestaltung der App-Nutzung.
Sie können die Einstellungen Ihres mobilen Betriebssystems und der App nach Ihren Wünschen konfigurieren und zum Beispiel die Annahme von Third--Party-Cookies oder allen Cookies ablehnen. Wir weisen Sie jedoch darauf hin, dass sie in diesem Fall eventuell nicht mehr alle Funktionen unserer mobilen App nutzen können.

6) Erhebung von Standortdaten
Mit Einwilligung
Unser Angebot umfasst sog. Location Based Services, mit welchen wir Ihnen spezielle Angebote bieten, die auf ihren jeweiligen Standort zugeschnitten sind. Diese Funktion können Sie erst nutzen, nachdem sie über ein Pop-up zugestimmt haben, dass wir zu Zwecken der Leistungserbringung ihrer Standortdaten mittels GPS und Ihre IP-Adresse in anonymisierter Form erheben können. Sie können die Funktion in den Einstellungen der App oder ihres mobilen Betriebssystems jederzeit erlauben oder widerrufen. Ihr Standort wird nur an uns übertragen, wenn sie bei Nutzung der App Funktionen in Anspruch nehmen, die wir Ihnen nur bei Kenntnis ihres Standortes anbieten können.

7) Kontaktaufnahme
Im Rahmen der Kontaktaufnahme mit uns (z.B. per Kontaktformular oder E-Mail) werden personenbezogene Daten erhoben. Welche Daten im Falle der Nutzung eines Kontaktformulars erhoben werden, ist aus dem jeweiligen Kontaktformular in der App ersichtlich. Diese Daten werden ausschließlich zum Zweck der Beantwortung Ihres Anliegens bzw. für die Kontaktaufnahme und die damit verbundene technische Administration gespeichert und verwendet. Rechtsgrundlage für die Verarbeitung dieser Daten ist unser berechtigtes Interesse an der Beantwortung Ihres Anliegens gemäß Art. 6 Abs. 1 lit. f DSGVO. Zielt Ihre Kontaktierung auf den Abschluss eines Vertrages ab, so ist zusätzliche Rechtsgrundlage für die Verarbeitung Art. 6 Abs. 1 lit. b DSGVO. Ihre Daten werden nach abschließender Bearbeitung Ihrer Anfrage gelöscht. Dies ist der Fall, wenn sich aus den Umständen entnehmen lässt, dass der betroffene Sachverhalt abschließend geklärt ist und sofern keine gesetzlichen Aufbewahrungspflichten entgegenstehen.

8) Datenverarbeitung zur Vertragsabwicklung
8.1 Zur Abwicklung von über die App geschlossenen Verträgen arbeiten wir mit dem / den nachstehenden Dienstleistern zusammen, die uns ganz oder teilweise bei der Durchführung geschlossener Verträge unterstützen. An diese Dienstleister werden nach Maßgabe der folgenden Informationen gewisse personenbezogene Daten übermittelt.
Die von uns erhobenen personenbezogenen Daten werden im Rahmen der Vertragsabwicklung an das mit der Lieferung beauftragte Transportunternehmen weitergegeben, soweit dies zur Lieferung der Ware erforderlich ist. Ihre Zahlungsdaten geben wir im Rahmen der Zahlungsabwicklung an das beauftragte Kreditinstitut weiter, sofern dies für die Zahlungsabwicklung erforderlich ist. Sofern Zahlungsdienstleister eingesetzt werden, informieren wir Sie hierüber nachstehend explizit. Rechtsgrundlage für die Weitergabe der Daten ist Art. 6 Abs. 1 lit. b DSGVO.
8.2 Einsatz von speziellen Dienstleistern zur Vertragsbearbeitung und -abwicklung
- Billbee
Für die Bestellabwicklung nutzen wir den folgenden Anbieter: Billbee GmbH, Arolser Str. 10, 34477 Twistetal, Deutschland
Name, Anschrift sowie gegebenenfalls weitere personenbezogene Daten werden gemäß Art. 6 Abs. 1 lit. b DSGVO ausschließlich zum Zwecke der Abwicklung der Online-Bestellung an den Anbieter weitergegeben. Die Weitergabe Ihrer Daten erfolgt hierbei nur, soweit dies für die Abwicklung der Bestellung tatsächlich erforderlich ist.
8.3 - Apple Pay
Wenn Sie sich für die Zahlungsart „Apple Pay“ der Apple Distribution International (Apple), Hollyhill Industrial Estate, Hollyhill, Cork, Irland, entscheiden, erfolgt die Zahlungsabwicklung über die „Apple Pay“-Funktion Ihres mit iOS, watchOS oder macOS betriebenen Endgerätes durch die Belastung einer bei „Apple Pay“ hinterlegten Zahlungskarte. Apple Pay verwendet hierbei Sicherheitsfunktionen, die in die Hardware und Software Ihres Geräts integriert sind, um Ihre Transaktionen zu schützen. Für die Freigabe einer Zahlung ist somit die Eingabe eines zuvor durch Sie festgelegten Codes sowie die Verifizierung mittels der „Face ID“- oder „Touch ID“ – Funktion ihres Endgerätes erforderlich.
Zum Zwecke der Zahlungsabwicklung werden Ihre im Rahmen des Bestellvorgangs mitgeteilten Informationen nebst den Informationen über Ihre Bestellung in verschlüsselter Form an Apple weitergegeben. Apple verschlüsselt diese Daten sodann erneut mit einem entwicklerspezifischen Schlüssel, bevor die Daten zur Durchführung der Zahlung an den Zahlungsdienstleister der in Apple Pay hinterlegten Zahlungskarte übermittelt werden. Die Verschlüsselung sorgt dafür, dass nur die Website, über die der Einkauf getätigt wurde, auf die Zahlungsdaten zugreifen kann. Nachdem die Zahlung getätigt wurde, sendet Apple zur Bestätigung des Zahlungserfolges Ihre Geräteaccountnummer sowie einen transaktionsspezifischen, dynamischen Sicherheitscode an die Ausgangswebsite.
Sofern bei den beschriebenen Übermittlungen personenbezogene Daten verarbeitet werden, erfolgt die Verarbeitung ausschließlich zum Zwecke der Zahlungsabwicklung gemäß Art. 6 Abs. 1 lit. b DSGVO.
Apple bewahrt anonymisierte Transaktionsdaten auf, darunter der ungefähre Kaufbetrag, das ungefähre Datum und die ungefähre Uhrzeit sowie die Angabe, ob die Transaktion erfolgreich abgeschlossen wurde. Durch die Anonymisierung wird ein Personenbezug vollständig ausgeschlossen. Apple nutzt die anonymisierten Daten zur Verbesserung von „Apple Pay“ und anderen Apple-Produkten und Diensten.
Wenn Sie Apple Pay auf dem iPhone oder der Apple Watch zum Abschluss eines Kaufs verwenden, den Sie über Safari auf dem Mac getätigt haben, kommunizieren der Mac und das Autorisierungsgerät über einen verschlüsselten Kanal auf den Apple-Servern. Apple verarbeitet oder speichert keine dieser Informationen in einem Format, mit dem Ihre Person identifiziert werden kann. Sie können die Möglichkeit zur Verwendung von Apple Pay auf Ihrem Mac in den Einstellungen Ihres iPhone deaktivieren. Gehen Sie zu „Wallet & Apple Pay", und deaktivieren Sie „Zahlungen auf Mac erlauben".
Weitere Hinweise zum Datenschutz bei Apple Pay finden Sie unter der nachstehenden Internetadresse: https://support.apple.com/de-de/HT203027
- Google Pay
Wenn Sie sich für die Zahlungsart „Google Pay“ der Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland („Google“) entscheiden, erfolgt die Zahlungsabwicklung über die „Google Pay“-Applikation Ihres mit mindestens Android 4.4 („KitKat“) betriebenen und über eine NFC-Funktion verfügenden mobilen Endgeräts durch die Belastung einer bei Google Pay hinterlegten Zahlungskarte oder einem dort verifizierten Bezahlsystem (z.B. PayPal). Für die Freigabe einer Zahlung über Google Pay in Höhe von mehr als 25,- € ist das vorherige Entsperren Ihres mobilen Endgerätes durch die jeweils eingerichtete Verifikationsmaßnahme (etwa Gesichtserkennung, Passwort, Fingerabdruck oder Muster) erforderlich.
Zum Zwecke der Zahlungsabwicklung werden Ihre im Rahmen des Bestellvorgangs mitgeteilten Informationen nebst den Informationen über Ihre Bestellung an Google weitergegeben. Google übermittelt sodann Ihre in Google Pay hinterlegten Zahlungsinformationen in Form einer einmalig vergebenen Transaktionsnummer an die Ausgangswebsite, mit der eine erfolgte Zahlung verifiziert wird. Diese Transaktionsnummer enthält keinerlei Informationen zu den realen Zahldaten Ihrer bei Google Pay hinterlegten Zahlungsmittel, sondern wird als einmalig gültiger numerischer Token erstellt und übermittelt. Bei sämtlichen Transaktionen über Google Pay tritt Google lediglich als Vermittler zur Abwicklung des Bezahlvorgangs auf. Die Durchführung der Transaktion erfolgt ausschließlich im Verhältnis zwischen dem Nutzer und der Ausgangswebsite durch Belastung des bei Google Pay hinterlegten Zahlungsmittels.
Sofern bei den beschriebenen Übermittlungen personenbezogene Daten verarbeitet werden, erfolgt die Verarbeitung ausschließlich zum Zwecke der Zahlungsabwicklung gemäß Art. 6 Abs. 1 lit. b DSGVO.
Google behält sich vor, bei jeder über Google Pay getätigten Transaktion bestimmte vorgangsspezifische Informationen zu erheben, zu speichern und auszuwerten. Hierzu gehören Datum, Uhrzeit und Betrag der Transaktion, Händlerstandort und -beschreibung, eine vom Händler bereitgestellte Beschreibung der gekauften Waren oder Dienste, Fotos, die Sie der Transaktion beigefügt haben, der Name und die E-Mail-Adresse des Verkäufers und Käufers bzw. des Absenders und Empfängers, die verwendete Zahlungsmethode, Ihre Beschreibung für den Grund der Transaktion sowie gegebenenfalls das mit der Transaktion verbundene Angebot.
Laut Google erfolgt diese Verarbeitung ausschließlich gemäß Art. 6 Abs.1 lit. f DSGVO auf Basis des berechtigten Interesses an der ordnungsgemäßen Rechnungslegung, der Verifizierung von Vorgangsdaten und der Optimierung und Funktionserhaltung des Google Pay-Dienstes.
Google behält sich außerdem vor, die verarbeiteten Vorgangsdaten mit weiteren Informationen zusammenzuführen, die bei der Nutzung weiterer Google-Dienste durch Google erhoben und gespeichert werden.
Die Nutzungsbedingungen von Google Pay finden sich hier:
https://payments.google.com/payments/apis-secure/u/0/get_legal_document?ldo=0&ldt=googlepaytos&ldl=de
Weitere Hinweise zum Datenschutz bei Google Pay finden Sie unter der nachstehenden Internetadresse:
https://payments.google.com/payments/apis-secure/get_legal_document?ldo=0&ldt=privacynotice&ldl=de
- Paypal
Auf dieser Website stehen eine oder mehrere Online-Zahlungsarten des folgenden Anbieters zur Verfügung: PayPal (Europe) S.a.r.l. et Cie, S.C.A., 22-24 Boulevard Royal, L-2449 Luxemburg
Bei Auswahl einer Zahlungsart des Anbieters, bei der Sie in Vorleistung gehen, werden an diesen Ihre im Rahmen des Bestellvorgangs mitgeteilten Zahlungsdaten (darunter Name, Anschrift, Bank- und Zahlkarteninformationen, Währung und Transaktionsnummer) sowie Informationen über den Inhalt Ihrer Bestellung gemäß Art. 6 Abs. 1 lit. b DSGVO weitergegeben. Die Weitergabe Ihrer Daten erfolgt in diesem Falle ausschließlich zum Zweck der Zahlungsabwicklung mit dem Anbieter und nur insoweit, als sie hierfür erforderlich ist.
Bei Auswahl einer Zahlungsart, bei der wir in Vorleistung gehen, werden Sie im Bestellablauf auch aufgefordert, bestimmte persönliche Daten (Vor- und Nachname, Straße, Hausnummer, Postleitzahl, Ort, Geburtsdatum, E-Mail-Adresse, Telefonnummer, ggf. Daten zu einem alternativen Zahlungsmittel) anzugeben.
Um in solchen Fällen unser berechtigtes Interesse an der Feststellung Ihrer Zahlungsfähigkeit zu wahren, werden diese Daten von uns gemäß Art. 6 Abs. 1 lit. f DSGVO zum Zwecke einer Bonitätsprüfung an den Anbieter weitergeleitet. Der Anbieter prüft auf Basis der von Ihnen angegebenen persönlichen Daten sowie weiterer Daten (wie etwa Warenkorb, Rechnungsbetrag, Bestellhistorie, Zahlungserfahrungen), ob die von Ihnen ausgewählte Zahlungsmöglichkeit im Hinblick auf Zahlungs- und/oder Forderungsausfallrisiken gewährt werden kann.
Die Bonitätsauskunft kann Wahrscheinlichkeitswerte enthalten (sog. Score-Werte). Soweit Score-Werte in das Ergebnis der Bonitätsauskunft einfließen, haben sie ihre Grundlage in einem wissenschaftlich anerkannten mathematisch-statistischen Verfahren. In die Berechnung der Score-Werte fließen unter anderem, aber nicht ausschließlich, Anschriftendaten ein.
Sie können dieser Verarbeitung Ihrer Daten jederzeit durch eine Nachricht an uns oder gegenüber dem Anbieter widersprechen. Jedoch bleibt der Anbieter ggf. weiterhin berechtigt, Ihre personenbezogenen Daten zu verarbeiten, sofern dies zur vertragsgemäßen Zahlungsabwicklung erforderlich ist.
- Stripe
Wenn Sie sich für eine Zahlungsart des Paymentdienstleisters Stripe entscheiden, erfolgt die Zahlungsabwicklung über den Paymentdienstleister Stripe Payments Europe Ltd., 1 Grand Canal Street Lower, Grand Canal Dock, Dublin, Irland, an den wir Ihre im Rahmen des Bestellvorgangs mitgeteilten Informationen nebst den Informationen über Ihre Bestellung (Name, Anschrift, Kontonummer, Bankleitzahl, evtl. Kreditkartennummer, Rechnungsbetrag, Währung und Transaktionsnummer) gemäß Art. 6 Abs. 1 lit. b DSGVO weitergeben. Die Weitergabe Ihrer Daten erfolgt ausschließlich zum Zwecke der Zahlungsabwicklung mit dem Payment-Dienstleister Stripe Payments Europe Ltd. und nur insoweit, als sie hierfür erforderlich ist. Nähere Informationen zum Datenschutz von Stripe finden Sie unter der URL https://stripe.com/de/privacy#translation.

9) Registrierung in der App
Sie können sich in unserer App unter Angabe von personenbezogenen Daten registrieren. Welche personenbezogenen Daten für die Registrierung verarbeitet werden, ergibt sich aus der Eingabemaske, die für die Registrierung verwendet wird. Wir verwenden für die Registrierung das sog. Double-opt-in-Verfahren, d. h. Ihre Registrierung ist erst abgeschlossen, wenn Sie zuvor Ihre Anmeldung über eine Ihnen zu diesem Zweck zugesandte Bestätigungs-E-Mail durch Klick auf den darin enthaltenen Link bestätigt haben. Falls Ihre diesbezügliche Bestätigung nicht binnen 24 Stunden erfolgt, wird Ihre Anmeldung automatisch aus unserer Datenbank gelöscht. Die Angabe der zuvor genannten Daten ist verpflichtend. Alle weiteren Informationen können Sie freiwillig durch Nutzung unseres Portals bereitstellen.
Wenn Sie unsere App nutzen, speichern wir Ihre zur Vertragserfüllung erforderlichen Daten, auch evtl. Angaben zur Zahlungsweise, bis Sie Ihren Zugang endgültig löschen. Weiterhin speichern wir die von Ihnen freiwillig angegebenen Daten für die Zeit Ihrer Nutzung des Portals, soweit Sie diese nicht zuvor löschen. Alle Angaben können Sie im geschützten Kundenbereich verwalten und ändern. Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO.
Darüber hinaus speichern wir alle von Ihnen veröffentlichten Inhalte (wie z.B. öffentliche Beiträge, Pinnwandeinträge, Gästebucheintragungen, etc.) um die App zu betreiben. Wir haben ein berechtigtes Interesse in der der Bereitstellung der App mit dem vollständigen User-Generated-Content. Die Rechtsgrundlage hierfür ist Art. 6 Abs. 1 lit. f DSGVO. Wenn Sie Ihren Account löschen, bleiben Ihre insbesondere im Forum veröffentlichten Äußerungen weiterhin für alle Leser sichtbar, Ihr Account ist jedoch nicht mehr abrufbar. Alle übrigen Daten werden in diesem Fall gelöscht.

10) Nutzung Ihrer Daten zur Direktwerbung
10.1 Anmeldung zu unserem E-Mail-Newsletter
Wenn Sie sich zu unserem E-Mail Newsletter anmelden, übersenden wir Ihnen regelmäßig Informationen zu unseren Angeboten. Pflichtangabe für die Übersendung des Newsletters ist allein Ihre E-Mailadresse. Die Angabe weiterer Daten ist freiwillig und wird verwendet, um Sie persönlich ansprechen zu können. Für den Versand des Newsletters verwenden wir das sog. Double Opt-in Verfahren. Dies bedeutet, dass wir Ihnen erst dann einen E-Mail Newsletter übermitteln werden, wenn Sie uns ausdrücklich bestätigt haben, dass Sie in den Empfang von Newsletter einwilligen. Wir schicken Ihnen dann eine Bestätigungs-E-Mail, mit der Sie gebeten werden durch Anklicken eines entsprechenden Links zu bestätigen, dass Sie künftig den Newsletter erhalten wollen.
Mit der Aktivierung des Bestätigungslinks erteilen Sie uns Ihre Einwilligung für die Nutzung Ihrer personenbezogenen Daten gemäß Art. 6 Abs. 1 lit. a DSGVO. Bei der Anmeldung zum Newsletter speichern wir Ihre vom Internet Service-Provider (ISP) eingetragene IP-Adresse sowie das Datum und die Uhrzeit der Anmeldung, um einen möglichen Missbrauch Ihrer E-Mail- Adresse zu einem späteren Zeitpunkt nachvollziehen zu können. Die von uns bei der Anmeldung zum Newsletter erhobenen Daten werden ausschließlich für Zwecke der werblichen Ansprache im Wege des Newsletters benutzt. Sie können den Newsletter jederzeit über den dafür vorgesehenen Link im Newsletter oder durch entsprechende Nachricht an den eingangs genannten Verantwortlichen abbestellen. Nach erfolgter Abmeldung wird Ihre E-Mailadresse unverzüglich in unserem Newsletter-Verteiler gelöscht, soweit Sie nicht ausdrücklich in eine weitere Nutzung Ihrer Daten eingewilligt haben oder wir uns eine darüberhinausgehende Datenverwendung vorbehalten, die gesetzlich erlaubt ist und über die wir Sie in dieser Erklärung informieren.
10.2 Versand des E-Mail-Newsletters an Bestandskunden
Wenn Sie uns Ihre E-Mailadresse beim Kauf von Waren bzw. Dienstleistungen zur Verfügung gestellt haben, behalten wir uns vor, Ihnen regelmäßig Angebote zu ähnlichen Waren bzw. Dienstleistungen, wie den bereits gekauften, aus unserem Sortiment per E-Mail zuzusenden. Hierfür müssen wir gemäß § 7 Abs. 3 UWG keine gesonderte Einwilligung von Ihnen einholen. Die Datenverarbeitung erfolgt insoweit allein auf Basis unseres berechtigten Interesses an personalisierter Direktwerbung gemäß Art. 6 Abs. 1 lit. f DSGVO. Haben Sie der Nutzung Ihrer E-Mailadresse zu diesem Zweck anfänglich widersprochen, findet ein Mailversand unsererseits nicht statt.
Sie sind berechtigt, der Nutzung Ihrer E-Mailadresse zu dem vorbezeichneten Werbezweck jederzeit mit Wirkung für die Zukunft durch eine Mitteilung an den zu Beginn genannten Verantwortlichen zu widersprechen. Hierfür fallen für Sie lediglich Übermittlungskosten nach den Basistarifen an. Nach Eingang Ihres Widerspruchs wird die Nutzung Ihrer E-Mailadresse zu Werbezwecken unverzüglich eingestellt.
10.3 Klaviyo
Der Versand unserer E-Mail-Newsletter und sonstiger werblicher E-Mail-Kommunikation erfolgt über diesen Anbieter: Klaviyo, Inc., 125 Summer St., Ste 600, Boston, MA 02110, USA
Auf Basis unseres berechtigten Interesses an einem effektiven und nutzerfreundlichen E-Mail-Marketing geben wir Ihre bei der Anmeldung bereitgestellten Daten gem. Art. 6 Abs. 1 lit. f DSGVO an diesen Anbieter weiter, damit dieser den Mailversand in unserem Auftrag übernimmt.
Vorbehaltlich Ihrer ausdrücklichen Einwilligung gem. Art. 6 Abs. 1 lit. a DSGVO führt der Anbieter darüber hinaus eine statistische Erfolgsauswertung von Mail-Kampagnen mittels Web Beacons bzw. Zählpixel in den versendeten E-Mails durch, die Öffnungsraten und spezifische Interaktionen mit den Inhalten des Newsletters messen können. Dabei werden auch Endgeräteinformationen (z.B. Zeitpunkt des Aufrufs, IP-Adresse, Browsertyp und Betriebssystem) erhoben und ausgewertet, aber nicht mit anderen Datenbeständen zusammengeführt.
Ihre Einwilligung zum Mail-Tracking können Sie jederzeit mit Wirkung für die Zukunft widerrufen.
Wir haben mit dem Anbieter einen Auftragsverarbeitungsvertrag geschlossen, der die Daten unserer Seitenbesucher schützt und eine Weitergabe an Dritte untersagt.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt.

11) Webanalysedienste
Google (Universal) Analytics
Diese App benutzt Google (Universal) Analytics, einen Webanalysedienst der Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland ("Google"), der eine Analyse Ihrer Benutzung unserer App ermöglicht.
Standardmäßig werden beim Besuch der App durch Google (Universal) Analytics Cookies gesetzt, die als kleine Textbausteine auf Ihrem Endgerät abgelegt werden und bestimmte Informationen erheben. Zum Umfang dieser Informationen gehört auch Ihre IP-Adresse, die allerdings von Google um die letzten Ziffern gekürzt wird, um eine direkte Personenbeziehbarkeit auszuschließen.
Die Informationen werden an Server von Google übertragen und dort weiterverarbeitet. Dabei sind auch Übermittlungen an Google LLC mit Sitz in den USA möglich.
Google nutzt die erhobenen Informationen in unserem Auftrag, um Ihre Nutzung der App auszuwerten, Reports über die Appaktivitäten für uns zusammenzustellen und um weitere mit der App-Nutzung und der Internetnutzung verbundene Dienstleistungen zu erbringen. Die im Rahmen von Google Analytics von Ihrem Browser übermittelte und gekürzte IP-Adresse wird nicht mit anderen Daten von Google zusammengeführt. Die im Rahmen der Nutzung von Google (Universal) Analytics erhobenen Daten werden für die Dauer von zwei Monaten gespeichert und anschließend gelöscht.
Alle vorstehend beschriebenen Verarbeitungen, insbesondere das Setzen von Cookies auf dem verwendeten Endgerät, erfolgen nur, wenn Sie uns hierfür Ihre ausdrückliche Einwilligung gem. Art. 6 Abs. 1 lit. a DSGVO erteilt haben.
Ohne Ihre Einwilligung unterbleibt der Einsatz von Google (Universal) Analytics während Ihres Seitenbesuchs. Sie können Ihre erteilte Einwilligung mit Wirkung für die Zukunft jederzeit widerrufen. Um Ihr Widerrufsrecht auszuüben, deaktivieren Sie bitte diesen Dienst über das in der App bereitgestellte „Cookie-Consent-Tool“.
Wir haben mit Google einen Auftragsverarbeitungsvertrag geschlossen, der den Schutz der Daten unserer Seitenbesucher sicherstellt und eine unberechtigte Weitergabe an Dritte untersagt.
Weitere rechtliche Hinweise zu Google (Universal) Analytics finden Sie unter https://business.safety.google/intl/de/privacy/, https://policies.google.com/privacy?hl=de&gl=de und unter https://policies.google.com/technologies/partner-sites
Demografische Merkmale
Google (Universal) Analytics nutzt die spezielle Funktion „demografische Merkmale“ und kann darüber Statistiken erstellen, die Aussagen über das Alter, Geschlecht und Interessen von Seitenbesuchern treffen. Dies geschieht durch die Analyse von Werbung und Informationen von Drittanbietern. Dadurch können Zielgruppen für Marketingaktivitäten identifiziert werden. Die gesammelten Daten können jedoch keiner bestimmten Person zugeordnet werden und werden nach einer Speicherung für die Dauer von zwei Monaten gelöscht.
Google Signals
Als Erweiterung zu Google (Universal) Analytics kann in dieser App Google Signals verwendet werden, um geräteübergreifende Berichte erstellen zu lassen. Wenn Sie personalisierte Anzeigen aktiviert haben und Ihre Geräte mit Ihrem Google-Konto verknüpft haben, kann Google vorbehaltlich Ihrer Einwilligung zur Nutzung von Google Analytics gem. Art. 6 Abs. 1 lit. a DSGVO Ihr Nutzungsverhalten geräteübergreifend analysieren und Datenbankmodelle, unter anderem zu geräteübergreifenden Conversions, erstellen. Wir erhalten keine personenbezogenen Daten von Google, sondern nur Statistiken. Wenn Sie die geräteübergreifende Analyse stoppen möchten, können Sie die Funktion "Personalisierte Werbung" in den Einstellungen Ihres Google-Kontos deaktivieren. Folgen Sie dazu den Anweisungen auf dieser Seite: https://support.google.com/ads/answer/2662922?hl=de Weitere Informationen zu Google Signals finden Sie unter folgendem Link: https://support.google.com/analytics/answer/7532985?hl=de
UserIDs
Als Erweiterung zu Google (Universal) Analytics kann in dieser App die Funktion "UserIDs" verwendet werden. Wenn Sie in die Nutzung von Google (Universal) Analytics gem. Art. 6 Abs. 1 lit. a DSGVO eingewilligt, ein Konto in dieser App eingerichtet haben und sich auf verschiedenen Geräten mit diesem Konto anmelden, können Ihre Aktivitäten, darunter auch Conversions, geräteübergreifend analysiert werden.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt.

12) Tools und Sonstiges
12.1 Google Maps
Diese App nutzt einen Online-Kartendienst des folgenden Anbieters: Google Maps (API) von Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland (“Google”).
Google Maps ist ein Webdienst zur Darstellung von interaktiven (Land-)Karten, um geographische Informationen visuell darzustellen. Über die Nutzung dieses Dienstes wird Ihnen unser Standort angezeigt und eine etwaige Anfahrt erleichtert.
Bereits beim Aufrufen derjenigen App-Gestaltungen, in die die Karte von Google Maps eingebunden ist, werden Informationen über Ihre Nutzung unserer App (wie z.B. Ihre IP-Adresse) an Server von Google übertragen und dort gespeichert, hierbei kann es auch zu einer Übermittlung an die Server der Google LLC. in den USA kommen. Dies erfolgt unabhängig davon, ob Google ein Nutzerkonto bereitstellt, über das Sie eingeloggt sind oder ob ein Nutzerkonto besteht. Wenn Sie bei Google eingeloggt sind, werden Ihre Daten direkt Ihrem Konto zugeordnet. Wenn Sie die Zuordnung mit Ihrem Profil bei Google nicht wünschen, müssen Sie sich vor Aktivierung des Buttons ausloggen. Google speichert Ihre Daten (selbst für nicht eingeloggte Nutzer) als Nutzungsprofile und wertet diese aus.
Die Erhebung, Speicherung und die Auswertung erfolgen gemäß Art. 6 Abs. 1 lit. f DSGVO auf Basis des berechtigten Interesses von Google an der Einblendung personalisierter Werbung, Marktforschung und/oder der bedarfsgerechten Gestaltung von Google-Websites. Ihnen steht ein Widerspruchsrecht gegen die Bildung dieser Nutzerprofile zu, wobei Sie sich für dessen Ausübung an Google wenden müssen. Wenn Sie mit der künftigen Übermittlung Ihrer Daten an Google im Rahmen der Nutzung von Google Maps nicht einverstanden sind, besteht auch die Möglichkeit, den Webdienst von Google Maps vollständig zu deaktivieren, indem Sie die Anwendung JavaScript in Ihrem Browser ausschalten. Google Maps und damit auch die Kartenanzeige auf dieser Internetseite kann dann nicht genutzt werden.
Soweit rechtlich erforderlich, haben wir zur vorstehend dargestellten Verarbeitung Ihrer Daten Ihre Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO eingeholt. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen. Um Ihren Widerruf auszuüben, befolgen Sie bitte die vorstehend geschilderte Möglichkeit zur Vornahme eines Widerspruchs.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt.
Weitere Informationen zu den Datenschutzbestimmungen von Google finden sich hier: https://business.safety.google/intl/de/privacy/ und https://policies.google.com/privacy
12.2 Google Web Fonts
Diese App nutzt zur einheitlichen Darstellung von Schriftarten sogenannte Web Fonts des folgenden Anbieters: Google Ireland Limited, Gordon House, 4 Barrow St, Dublin, D04 E5W5, Irland
Bei Nutzung dieser App werden die benötigten Web Fonts geladen, um Texte und Schriftarten korrekt anzuzeigen und stellt eine direkte Verbindung zu den Servern des Anbieters her. Hierbei werden bestimmte Browserinformationen, einschließlich Ihrer IP-Adresse, an den Anbieter übermittelt.
Daten können zudem übermittelt werden an: Google LLC, USA
Die Verarbeitung von personenbezogenen Daten im Zuge der Verbindungsaufnahme mit dem Anbieter der Schriftarten wird nur dann vollzogen, wenn Sie uns gemäß Art. 6 Abs. 1 lit. a DSGVO dazu Ihre ausdrückliche Einwilligung erteilt haben. Sie können Ihre erteilte Einwilligung jederzeit mit Wirkung für die Zukunft widerrufen, indem Sie diesen Dienst über das in der App bereitgestellte „Cookie-Consent-Tool“ deaktivieren. Falls Ihr Browser keine Web Fonts unterstützt, wird eine Standardschrift von Ihrem Computer genutzt.
Für Datenübermittlungen in die USA hat sich der Anbieter dem EU-US-Datenschutzrahmen (EU-US Data Privacy Framework) angeschlossen, das auf Basis eines Angemessenheitsbeschlusses der Europäischen Kommission die Einhaltung des europäischen Datenschutzniveaus sicherstellt.
Weitere Informationen zu den Datenschutzbestimmungen von Google finden sich hier: https://business.safety.google/intl/de/privacy/ und https://policies.google.com/privacy

13) Rechte des Betroffenen
13.1 Das geltende Datenschutzrecht gewährt Ihnen gegenüber dem Verantwortlichen hinsichtlich der Verarbeitung Ihrer personenbezogenen Daten umfassende Betroffenenrechte (Auskunfts- und Interventionsrechte), über die wir Sie nachstehend informieren:
- Auskunftsrecht gemäß Art. 15 DSGVO: Sie haben insbesondere ein Recht auf Auskunft über Ihre von uns verarbeiteten personenbezogenen Daten, die Verarbeitungszwecke, die Kategorien der verarbeiteten personenbezogenen Daten, die Empfänger oder Kategorien von Empfängern, gegenüber denen Ihre Daten offengelegt wurden oder werden, die geplante Speicherdauer bzw. die Kriterien für die Festlegung der Speicherdauer, das Bestehen eines Rechts auf Berichtigung, Löschung, Einschränkung der Verarbeitung, Widerspruch gegen die Verarbeitung, Beschwerde bei einer Aufsichtsbehörde, die Herkunft Ihrer Daten, wenn diese nicht durch uns bei Ihnen erhoben wurden, das Bestehen einer automatisierten Entscheidungsfindung einschließlich Profiling und ggf. aussagekräftige Informationen über die involvierte Logik und die Sie betreffende Tragweite und die angestrebten Auswirkungen einer solchen Verarbeitung, sowie Ihr Recht auf Unterrichtung, welche Garantien gemäß Art. 46 DSGVO bei Weiterleitung Ihrer Daten in Drittländer bestehen;
- Recht auf Berichtigung gemäß Art. 16 DSGVO: Sie haben ein Recht auf unverzügliche Berichtigung Sie betreffender unrichtiger Daten und/oder Vervollständigung Ihrer bei uns gespeicherten unvollständigen Daten;
- Recht auf Löschung gemäß Art. 17 DSGVO: Sie haben das Recht, die Löschung Ihrer personenbezogenen Daten bei Vorliegen der Voraussetzungen des Art. 17 Abs. 1 DSGVO zu verlangen. Dieses Recht besteht jedoch insbesondere dann nicht, wenn die Verarbeitung zur Ausübung des Rechts auf freie Meinungsäußerung und Information, zur Erfüllung einer rechtlichen Verpflichtung, aus Gründen des öffentlichen Interesses oder zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist;
- Recht auf Einschränkung der Verarbeitung gemäß Art. 18 DSGVO: Sie haben das Recht, die Einschränkung der Verarbeitung Ihrer personenbezogenen Daten zu verlangen, solange die von Ihnen bestrittene Richtigkeit Ihrer Daten überprüft wird, wenn Sie eine Löschung Ihrer Daten wegen unzulässiger Datenverarbeitung ablehnen und stattdessen die Einschränkung der Verarbeitung Ihrer Daten verlangen, wenn Sie Ihre Daten zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen benötigen, nachdem wir diese Daten nach Zweckerreichung nicht mehr benötigen oder wenn Sie Widerspruch aus Gründen Ihrer besonderen Situation eingelegt haben, solange noch nicht feststeht, ob unsere berechtigten Gründe überwiegen;
- Recht auf Unterrichtung gemäß Art. 19 DSGVO: Haben Sie das Recht auf Berichtigung, Löschung oder Einschränkung der Verarbeitung gegenüber dem Verantwortlichen geltend gemacht, ist dieser verpflichtet, allen Empfängern, denen die Sie betreffenden personenbezogenen Daten offengelegt wurden, diese Berichtigung oder Löschung der Daten oder Einschränkung der Verarbeitung mitzuteilen, es sei denn, dies erweist sich als unmöglich oder ist mit einem unverhältnismäßigen Aufwand verbunden. Ihnen steht das Recht zu, über diese Empfänger unterrichtet zu werden.
- Recht auf Datenübertragbarkeit gemäß Art. 20 DSGVO: Sie haben das Recht, Ihre personenbezogenen Daten, die Sie uns bereitgestellt haben, in einem strukturierten, gängigen und maschinenlesbaren Format zu erhalten oder die Übermittlung an einen anderen Verantwortlichen zu verlangen, soweit dies technisch machbar ist;
- Recht auf Widerruf erteilter Einwilligungen gemäß Art. 7 Abs. 3 DSGVO: Sie haben das Recht, eine einmal erteilte Einwilligung in die Verarbeitung von Daten jederzeit mit Wirkung für die Zukunft zu widerrufen. Im Falle des Widerrufs werden wir die betroffenen Daten unverzüglich löschen, sofern eine weitere Verarbeitung nicht auf eine Rechtsgrundlage zur einwilligungslosen Verarbeitung gestützt werden kann. Durch den Widerruf der Einwilligung wird die Rechtmäßigkeit der aufgrund der Einwilligung bis zum Widerruf erfolgten Verarbeitung nicht berührt;
- Recht auf Beschwerde gemäß Art. 77 DSGVO: Wenn Sie der Ansicht sind, dass die Verarbeitung der Sie betreffenden personenbezogenen Daten gegen die DSGVO verstößt, haben Sie - unbeschadet eines anderweitigen verwaltungsrechtlichen oder gerichtlichen Rechtsbehelfs - das Recht auf Beschwerde bei einer Aufsichtsbehörde, insbesondere in dem Mitgliedstaat Ihres Aufenthaltsortes, Ihres Arbeitsplatzes oder des Ortes des mutmaßlichen Verstoßes.
13.2 WIDERSPRUCHSRECHT
WENN WIR IM RAHMEN EINER INTERESSENABWÄGUNG IHRE PERSONENBEZOGENEN DATEN AUFGRUND UNSERES ÜBERWIEGENDEN BERECHTIGTEN INTERESSES VERARBEITEN, HABEN SIE DAS JEDERZEITIGE RECHT, AUS GRÜNDEN, DIE SICH AUS IHRER BESONDEREN SITUATION ERGEBEN, GEGEN DIESE VERARBEITUNG WIDERSPRUCH MIT WIRKUNG FÜR DIE ZUKUNFT EINZULEGEN.
MACHEN SIE VON IHREM WIDERSPRUCHSRECHT GEBRAUCH, BEENDEN WIR DIE VERARBEITUNG DER BETROFFENEN DATEN. EINE WEITERVERARBEITUNG BLEIBT ABER VORBEHALTEN, WENN WIR ZWINGENDE SCHUTZWÜRDIGE GRÜNDE FÜR DIE VERARBEITUNG NACHWEISEN KÖNNEN, DIE IHRE INTERESSEN, GRUNDRECHTE UND GRUNDFREIHEITEN ÜBERWIEGEN, ODER WENN DIE VERARBEITUNG DER GELTENDMACHUNG, AUSÜBUNG ODER VERTEIDIGUNG VON RECHTSANSPRÜCHEN DIENT.
WERDEN IHRE PERSONENBEZOGENEN DATEN VON UNS VERARBEITET, UM DIREKTWERBUNG ZU BETREIBEN, HABEN SIE DAS RECHT, JEDERZEIT WIDERSPRUCH GEGEN DIE VERARBEITUNG SIE BETREFFENDER PERSONENBEZOGENER DATEN ZUM ZWECKE DERARTIGER WERBUNG EINZULEGEN. SIE KÖNNEN DEN WIDERSPRUCH WIE OBEN BESCHRIEBEN AUSÜBEN.
MACHEN SIE VON IHREM WIDERSPRUCHSRECHT GEBRAUCH, BEENDEN WIR DIE VERARBEITUNG DER BETROFFENEN DATEN ZU DIREKTWERBEZWECKEN.

14) Dauer der Speicherung personenbezogener Daten
Die Dauer der Speicherung von personenbezogenen Daten bemisst sich anhand der jeweiligen Rechtsgrundlage, am Verarbeitungszweck und – sofern einschlägig – zusätzlich anhand der jeweiligen gesetzlichen Aufbewahrungsfrist (z.B. handels- und steuerrechtliche Aufbewahrungsfristen).
Bei der Verarbeitung von personenbezogenen Daten auf Grundlage einer ausdrücklichen Einwilligung gemäß Art. 6 Abs. 1 lit. a DSGVO werden die betroffenen Daten so lange gespeichert, bis Sie Ihre Einwilligung widerrufen.
Existieren gesetzliche Aufbewahrungsfristen für Daten, die im Rahmen rechtsgeschäftlicher bzw. rechtsgeschäftsähnlicher Verpflichtungen auf der Grundlage von Art. 6 Abs. 1 lit. b DSGVO verarbeitet werden, werden diese Daten nach Ablauf der Aufbewahrungsfristen routinemäßig gelöscht, sofern sie nicht mehr zur Vertragserfüllung oder Vertragsanbahnung erforderlich sind und/oder unsererseits kein berechtigtes Interesse an der Weiterspeicherung fortbesteht.
Bei der Verarbeitung von personenbezogenen Daten auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO werden diese Daten so lange gespeichert, bis Sie Ihr Widerspruchsrecht nach Art. 21 Abs. 1 DSGVO ausüben, es sei denn, wir können zwingende schutzwürdige Gründe für die Verarbeitung nachweisen, die Ihre Interessen, Rechte und Freiheiten überwiegen, oder die Verarbeitung dient der Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen.
Bei der Verarbeitung von personenbezogenen Daten zum Zwecke der Direktwerbung auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO werden diese Daten so lange gespeichert, bis Sie Ihr Widerspruchsrecht nach Art. 21 Abs. 2 DSGVO ausüben.
Sofern sich aus den sonstigen Informationen dieser Erklärung über spezifische Verarbeitungssituationen nichts anderes ergibt, werden gespeicherte personenbezogene Daten im Übrigen dann gelöscht, wenn sie für die Zwecke, für die sie erhoben oder auf sonstige Weise verarbeitet wurden, nicht mehr notwendig sind.


Copyright-Hinweis: Diese Datenschutzerklärung wurde von den Fachanwälten der IT-Recht Kanzlei erstellt und ist urheberrechtlich geschützt (https://www.it-recht-kanzlei.de)

Stand: 25.02.2026, 09:54:35
`;
