// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/goldsucher-landing/Adventure.tsx": () => import("../components/mockups/goldsucher-landing/Adventure.tsx"),
  "./components/mockups/goldsucher-landing/Community.tsx": () => import("../components/mockups/goldsucher-landing/Community.tsx"),
  "./components/mockups/goldsucher-landing/Professional.tsx": () => import("../components/mockups/goldsucher-landing/Professional.tsx")
};
